import os
from tkinter import ttk
import tkinter as tk
root = tk.Tk()
root.title('分类树状结构案例')
tree = ttk.Treeview(root)
tree['columns'] = ('num','price')
tree.column('num',width=100)
tree.column('price',width=100)
tree.heading('num',text='数量')
tree.heading('price',text='单价(元)')
data1 = tree.insert('',0,text='2020/05/02')
tree.insert(data1,'end',text='北京君正',values=('200','98.34'))
tree.insert(data1,'end',text='紫光国微',values=('500','45.34'))
tree.insert(data1,'end',text='立讯精密',values=('2000','34.56'))
data2 = tree.insert('',1,text='2020/05/03')
tree.insert(data2,'end',text='贵州茅台',values=('200','1234.56'))
tree.insert(data2,'end',text='五粮液',values=('500','45.34'))
tree.insert(data2,'end',text='洋河股份',values=('2000','34'))
data3 = tree.insert('',1,text='2020/05/04')
tree.insert(data3,'end',text='中兴集团',values=('200','1234.56'))
tree.insert(data3,'end',text='大族激光',values=('500','45.34'))
tree.insert(data3,'end',text='片仔癀',values=('2000','145'))
tree.pack()
label_name = tk.LabelFrame(root,text='处理事项')
label_name.pack(side='left',expand='yes')
btn_save = tk.Button(label_name,text='保存',width=10)
btn_save.pack(side='left')
btn_select = tk.Button(label_name,text='查询',width=10)
btn_select.pack(side='left')
btn_del = tk.Button(label_name,text='删除',width=10)
btn_del.pack(side='left')
btn_update = tk.Button(label_name,text='更新',width=10)
btn_update.pack(side='left')
root.mainloop()